p8105_hw1_sdc2157
================
Stephanie Calluori
2023-10-04

``` r
library(tidyverse)
library(readxl)
```

# Importing Data

``` r
pols_month_raw <- 
  read_csv("data/pols-month.csv")
head(pols_month_raw)
sum(is.na(pols_month_raw))

snp_raw <-
  read_csv("data/snp.csv")
head(snp_raw)
sum(is.na(snp_raw))

unemployment_raw <-
  read_csv("data/unemployment.csv")
head(unemployment_raw)
sum(is.na(unemployment_raw))

mr_trash_raw <-
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N549")
head(mr_trash_raw)

prof_trash_raw <-
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M96")
head(prof_trash_raw)

gwyn_trash_raw <-
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:K108")
head(gwyn_trash_raw)

mci_amyloid_raw <-
  read_csv("data/mci_amyloid.csv", skip = 1, col_names = TRUE)
head(mci_amyloid_raw)
sum(is.na(mci_amyloid_raw))

mci_baseline_raw <- 
  read_csv("data/MCI_baseline.csv", skip = 1, col_names = TRUE)
head(mci_baseline_raw)
sum(is.na(mci_baseline_raw))
```

# Problem 1 - Under REVISION

``` r
month_df = 
  tibble(
    month_num = 1:12,
    month = c("jan", "feb", "mar", "apr", "may", "june", "july", "aug", "sept", "oct", "nov", "dec")
  )

pols_month_df <- pols_month_raw |>
  janitor::clean_names() |> 
  separate(mon, c("year", "month_num", "day"), "-", convert = TRUE) |> 
  mutate(prez = recode(
      prez_dem, 
      "0" = "gop", 
      "1" = "dem")) |> 
  left_join(x = _, y = month_df, by = "month_num") |> 
  select(year, month, everything(), -month_num, -day, -prez_gop, -prez_dem)

head(pols_month_df)
```

    ## # A tibble: 6 × 9
    ##    year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem prez 
    ##   <int> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>
    ## 1  1947 jan        23      51     253      23      45     198 dem  
    ## 2  1947 feb        23      51     253      23      45     198 dem  
    ## 3  1947 mar        23      51     253      23      45     198 dem  
    ## 4  1947 apr        23      51     253      23      45     198 dem  
    ## 5  1947 may        23      51     253      23      45     198 dem  
    ## 6  1947 june       23      51     253      23      45     198 dem

``` r
snp_df <- snp_raw |>
  janitor::clean_names() |> 
  mutate(date = lubridate::mdy(date)) |> 
  separate(date, c("year", "month_num", "day"), "-", convert = TRUE) |> 
  left_join(x = _, y = month_df, by = "month_num") |> 
  select(year, month, close, -month_num, -day)

head(snp_df)
```

    ## # A tibble: 6 × 3
    ##    year month close
    ##   <int> <chr> <dbl>
    ## 1  2015 july  2080.
    ## 2  2015 june  2063.
    ## 3  2015 may   2107.
    ## 4  2015 apr   2086.
    ## 5  2015 mar   2068.
    ## 6  2015 feb   2104.

``` r
unemployment_df <- unemployment_raw |> 
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent_unemployed"
  )

head(unemployment_df)
```

    ## # A tibble: 6 × 3
    ##    year month percent_unemployed
    ##   <dbl> <chr>              <dbl>
    ## 1  1948 jan                  3.4
    ## 2  1948 feb                  3.8
    ## 3  1948 mar                  4  
    ## 4  1948 apr                  3.9
    ## 5  1948 may                  3.5
    ## 6  1948 jun                  3.6

# Problem 2

First, we need to clean each of the Trash Wheel datasets.

``` r
mr_trash_df <- mr_trash_raw |> 
  janitor::clean_names() |> 
  rename(volume_cubic_yds = volume_cubic_yards, homes_powered_old = homes_powered) |> 
  mutate(wheel = "mr_trash",
         homes_powered = weight_tons*500/30,
         year = as.numeric(year)) |> 
  select(wheel, everything(), -homes_powered_old)

str(mr_trash_df)
```

    ## tibble [547 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ wheel           : chr [1:547] "mr_trash" "mr_trash" "mr_trash" "mr_trash" ...
    ##  $ dumpster        : num [1:547] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month           : chr [1:547] "May" "May" "May" "May" ...
    ##  $ year            : num [1:547] 2014 2014 2014 2014 2014 ...
    ##  $ date            : POSIXct[1:547], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons     : num [1:547] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yds: num [1:547] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles : num [1:547] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene     : num [1:547] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts : num [1:547] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles   : num [1:547] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ grocery_bags    : num [1:547] 584 496 1080 896 368 ...
    ##  $ chip_bags       : num [1:547] 1162 874 2032 1971 753 ...
    ##  $ sports_balls    : num [1:547] 7.2 5.2 6 6 7.2 5.2 3.2 6.4 5.6 7.2 ...
    ##  $ homes_powered   : num [1:547] 71.8 45.7 57.5 51.7 67.7 ...

``` r
head(mr_trash_df)
```

    ## # A tibble: 6 × 15
    ##   wheel    dumpster month  year date                weight_tons volume_cubic_yds
    ##   <chr>       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ## 1 mr_trash        1 May    2014 2014-05-16 00:00:00        4.31               18
    ## 2 mr_trash        2 May    2014 2014-05-16 00:00:00        2.74               13
    ## 3 mr_trash        3 May    2014 2014-05-16 00:00:00        3.45               15
    ## 4 mr_trash        4 May    2014 2014-05-17 00:00:00        3.1                15
    ## 5 mr_trash        5 May    2014 2014-05-17 00:00:00        4.06               18
    ## 6 mr_trash        6 May    2014 2014-05-20 00:00:00        2.71               13
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <dbl>, homes_powered <dbl>

The Mr. Trash Wheel data set contains 547 observations and 15 variables.
Variables include wheel, dumpster, month, year, date, weight_tons,
volume_cubic_yds, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, grocery_bags, chip_bags, sports_balls, homes_powered.
Data was collected from 2014 to 2022. During this time, Mr. Trash Wheel
collected about 1748 tons of trash, which powered approximately 29139
homes!

``` r
prof_trash_df <- prof_trash_raw |> 
  janitor::clean_names() |> 
  rename(volume_cubic_yds = volume_cubic_yards, homes_powered_old = homes_powered) |> 
  mutate(wheel = "prof_trash",
         homes_powered = weight_tons*500/30) |> 
  select(wheel, everything(), -homes_powered_old)

str(prof_trash_df)
```

    ## tibble [94 × 14] (S3: tbl_df/tbl/data.frame)
    ##  $ wheel           : chr [1:94] "prof_trash" "prof_trash" "prof_trash" "prof_trash" ...
    ##  $ dumpster        : num [1:94] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month           : chr [1:94] "January" "January" "February" "February" ...
    ##  $ year            : num [1:94] 2017 2017 2017 2017 2017 ...
    ##  $ date            : POSIXct[1:94], format: "2017-01-02" "2017-01-30" ...
    ##  $ weight_tons     : num [1:94] 1.79 1.58 2.32 3.72 1.45 1.71 1.82 2.37 2.64 2.78 ...
    ##  $ volume_cubic_yds: num [1:94] 15 15 18 15 15 15 15 15 15 15 ...
    ##  $ plastic_bottles : num [1:94] 1950 9540 8350 8590 7830 8210 9830 9240 9540 8230 ...
    ##  $ polystyrene     : num [1:94] 6080 11230 9210 1030 9950 ...
    ##  $ cigarette_butts : num [1:94] 19700 17600 12000 13000 16000 14000 17000 15000 17000 13000 ...
    ##  $ glass_bottles   : num [1:94] 8 14 19 21 18 23 26 14 28 22 ...
    ##  $ grocery_bags    : num [1:94] 3100 5630 6430 5870 7450 ...
    ##  $ chip_bags       : num [1:94] 15600 16700 12400 11030 15340 ...
    ##  $ homes_powered   : num [1:94] 29.8 26.3 38.7 62 24.2 ...

The Prof. Trash Wheel data set contains 94 observations and 14
variables. Variables include wheel, dumpster, month, year, date,
weight_tons, volume_cubic_yds, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, grocery_bags, chip_bags, homes_powered.
Data was collected from 2017 to 2022. During this time, Prof. Trash
Wheel collected about 190 tons of trash, which powered approximately
3169 homes!

``` r
gwyn_trash_df <- gwyn_trash_raw |> 
  janitor::clean_names() |> 
  rename(volume_cubic_yds = volume_cubic_yards, homes_powered_old = homes_powered) |> 
  mutate(wheel = "gwynnda_trash",
         homes_powered = weight_tons*500/30) |> 
  select(wheel, everything(), -homes_powered_old)

str(gwyn_trash_df)
```

    ## tibble [106 × 12] (S3: tbl_df/tbl/data.frame)
    ##  $ wheel           : chr [1:106] "gwynnda_trash" "gwynnda_trash" "gwynnda_trash" "gwynnda_trash" ...
    ##  $ dumpster        : num [1:106] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month           : chr [1:106] "July" "July" "July" "July" ...
    ##  $ year            : num [1:106] 2021 2021 2021 2021 2021 ...
    ##  $ date            : POSIXct[1:106], format: "2021-07-03" "2021-07-07" ...
    ##  $ weight_tons     : num [1:106] 0.93 2.26 1.62 1.76 1.53 2.06 1.9 2.16 2.6 3.21 ...
    ##  $ volume_cubic_yds: num [1:106] 15 15 15 15 15 15 15 15 15 15 ...
    ##  $ plastic_bottles : num [1:106] 1200 2000 1800 1000 2100 2400 2700 3000 980 240 ...
    ##  $ polystyrene     : num [1:106] 360 240 270 180 240 360 320 320 180 42 ...
    ##  $ cigarette_butts : num [1:106] 3400 3900 2900 2100 4000 3900 4200 4000 1800 400 ...
    ##  $ plastic_bags    : num [1:106] 1800 2200 2400 1800 2700 3000 3200 3600 1000 360 ...
    ##  $ homes_powered   : num [1:106] 15.5 37.7 27 29.3 25.5 ...

The Gwynnda Trash Wheel data set contains 106 observations and 12
variables. Variables include wheel, dumpster, month, year, date,
weight_tons, volume_cubic_yds, plastic_bottles, polystyrene,
cigarette_butts, plastic_bags, homes_powered. Data was collected from
2021 to 2022. During this time, Gwynnda Trash Wheel collected about 311
tons of trash, which powered approximately 5180 homes!

Next, we will combine the 3 Trash Wheel datasets into a single dataset.

``` r
trash_wheels_df <- bind_rows(mr_trash_df, prof_trash_df, gwyn_trash_df)

view(trash_wheels_df)
str(trash_wheels_df)
```

    ## tibble [747 × 16] (S3: tbl_df/tbl/data.frame)
    ##  $ wheel           : chr [1:747] "mr_trash" "mr_trash" "mr_trash" "mr_trash" ...
    ##  $ dumpster        : num [1:747] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month           : chr [1:747] "May" "May" "May" "May" ...
    ##  $ year            : num [1:747] 2014 2014 2014 2014 2014 ...
    ##  $ date            : POSIXct[1:747], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons     : num [1:747] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yds: num [1:747] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles : num [1:747] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene     : num [1:747] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts : num [1:747] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles   : num [1:747] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ grocery_bags    : num [1:747] 584 496 1080 896 368 ...
    ##  $ chip_bags       : num [1:747] 1162 874 2032 1971 753 ...
    ##  $ sports_balls    : num [1:747] 7.2 5.2 6 6 7.2 5.2 3.2 6.4 5.6 7.2 ...
    ##  $ homes_powered   : num [1:747] 71.8 45.7 57.5 51.7 67.7 ...
    ##  $ plastic_bags    : num [1:747] NA NA NA NA NA NA NA NA NA NA ...

The combined data set contains 747 observations and 16 variables.
Variables include wheel, dumpster, month, year, date, weight_tons,
volume_cubic_yds, plastic_bottles, polystyrene, cigarette_butts,
glass_bottles, grocery_bags, chip_bags, sports_balls, homes_powered,
plastic_bags. From 2014 to 2022, the three trash wheels collected a
total of 2249 tons of trash, which powered approximately 37488 homes!

Professor Trash Wheel collected a total of 190.12 tons of trash.

In July 2021, Gwynnda collected a total of 1.63^{4} cigarette butts.

# Problem 3

## MCI_Baseline data set

The first two rows of the raw mci_baseline data set contain a header and
the variable names. When importing the data set (see above), we skipped
the header in the first row and set col_names to TRUE, so we only
imported the variable names and observations. There were no NA values in
the data set. The period (“.”) in the age_at_onset indicated that the
participant never developed MCI.

We recoded the categorical variables of sex and apoe4 status, so the
values appeared as the category names instead of numbers.

``` r
num_recruited_original <- nrow(mci_baseline_raw)

mci_baseline_df <- mci_baseline_raw |> 
  janitor::clean_names() |> 
  mutate(sex = recode(sex, "0" = "female", "1" = "male"),
         apoe4 = recode(apoe4, "0" = "non_carrier", "1" = "carrier")) |> 
  filter(!(current_age == age_at_onset))

num_recruited_clean <- nrow(mci_baseline_df)

num_mci <- mci_baseline_df |> 
  filter(!(age_at_onset == ".")) |> 
  nrow()

num_apoe_female <- mci_baseline_df |> 
  filter(sex == "female" & apoe4 == "carrier") |> 
  nrow()

num_female <- mci_baseline_df |> 
  filter(sex == "female") |> 
  nrow()
```

483 participants were recruited into the study. When cleaning the data,
we removed participants who did not meet the inclusion criteria for the
study (participants had to be free of MCI at baseline). 1 participant
was found to have MCI at baseline. Thus, 482 participants were included
in our final analyses.

The average baseline age of participants was 65 years old with a
standard deviation of 3 years.

It was found that 96 participants (20%) developed MCI over the course of
the study. Of the 211 women in the study, 30% women were APOE4 carriers.

\#MCI_Amyloid data set

``` r
str(mci_amyloid_raw)
```

    ## spc_tbl_ [487 × 6] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ Study ID: num [1:487] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ Baseline: chr [1:487] "0.1105487" "0.107481183" "0.106087034" "0.109251358" ...
    ##  $ Time 2  : chr [1:487] NA "0.109157373" "0.108744509" "0.108699686" ...
    ##  $ Time 4  : chr [1:487] "0.109325197" "0.109457839" "0.106065035" "0.110540386" ...
    ##  $ Time 6  : chr [1:487] "0.104756131" "0.105729713" NA "0.107476797" ...
    ##  $ Time 8  : chr [1:487] "0.107257697" "0.10661845" "0.106152357" "0.111212209" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   `Study ID` = col_double(),
    ##   ..   Baseline = col_character(),
    ##   ..   `Time 2` = col_character(),
    ##   ..   `Time 4` = col_character(),
    ##   ..   `Time 6` = col_character(),
    ##   ..   `Time 8` = col_character()
    ##   .. )
    ##  - attr(*, "problems")=<externalptr>

``` r
nrow(mci_amyloid_raw)
```

    ## [1] 487

``` r
mci_amyloid_df <- mci_amyloid_raw |> 
  janitor::clean_names() |> 
  rename(id = study_id, time_to_visit_ir = baseline) |> 
  mutate(time_to_visit_ir = as.numeric(time_to_visit_ir), 
         time_2 = as.numeric(time_2),
         time_4 = as.numeric(time_4),
         time_6 = as.numeric(time_6),
         time_8 = as.numeric(time_8))
```

    ## Warning: There were 5 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `time_to_visit_ir = as.numeric(time_to_visit_ir)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.

``` r
str(mci_amyloid_df)
```

    ## tibble [487 × 6] (S3: tbl_df/tbl/data.frame)
    ##  $ id              : num [1:487] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ time_to_visit_ir: num [1:487] 0.111 0.107 0.106 0.109 0.108 ...
    ##  $ time_2          : num [1:487] NA 0.109 0.109 0.109 0.112 ...
    ##  $ time_4          : num [1:487] 0.109 0.109 0.106 0.111 0.115 ...
    ##  $ time_6          : num [1:487] 0.105 0.106 NA 0.107 0.107 ...
    ##  $ time_8          : num [1:487] 0.107 0.107 0.106 0.111 0.106 ...

``` r
nrow(mci_amyloid_df)
```

    ## [1] 487

``` r
mci_no_overlap_df <- anti_join(mci_baseline_df, mci_amyloid_df, join_by(id))

mci_intersection_df <- inner_join(mci_baseline_df, mci_amyloid_df, join_by(id))

write_csv(mci_intersection_df,"data/mci_intersection.csv")
```
