---
title: "p8105_hw1_sdc2157"
author: "Stephanie Calluori"
date: 2023-10-04
output: github_document
---

```{r, load_packages, message = FALSE}
library(tidyverse)
library(readxl)
```

# Importing Data
```{r, import_data, results = "hide", message = FALSE}
pols_month_raw <- 
  read_csv("data/pols-month.csv")
head(pols_month_raw)
sum(is.na(pols_month_raw))

snp_raw <-
  read_csv("data/snp.csv")
head(snp_raw)
sum(is.na(snp_raw))

unemployment_raw <-
  read_csv("data/unemployment.csv")
head(unemployment_raw)

mr_trash_raw <-
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 1, range = "A2:N549")
head(mr_trash_raw)

prof_trash_raw <-
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 2, range = "A2:M96")
head(prof_trash_raw)

gwynnda_raw <-
  read_excel("data/202207 Trash Wheel Collection Data.xlsx", sheet = 4, range = "A2:K108")
head(gwynnda_raw)

mci_amyloid_raw <-
  read_csv("data/mci_amyloid.csv")
head(mci_amyloid_raw)

mci_baseline_raw <- 
  read_csv("data/MCI_baseline.csv")
head(mci_baseline_raw)

```

# Problem 1

```{r, pols data exploration, include = FALSE}
pols_month_raw |>
  count(prez_gop)

pols_month_raw |>
  count(prez_dem)
```

```{r, pols cleaning}
month_df = 
  tibble(
    month_num = 1:12,
    month = c("jan", "feb", "mar", "apr", "may", "june", "july", "aug", "sept", "oct", "nov", "dec")
  )

pols_month_df <- pols_month_raw |>
  janitor::clean_names() |> 
  separate(mon, c("year", "month_num", "day"), "-", convert = TRUE) |> 
  mutate(prez = recode(
      prez_dem, 
      "0" = "gop", 
      "1" = "dem")) |> 
  left_join(x = _, y = month_df, by = "month_num") |> 
  select(year, month, everything(), -month_num, -day, -prez_gop, -prez_dem)

head(pols_month_df)

```

```{r, snp cleaning}
snp_df <- snp_raw |>
  janitor::clean_names() |> 
  mutate(date = lubridate::mdy(date)) |> 
  separate(date, c("year", "month_num", "day"), "-", convert = TRUE) |> 
  left_join(x = _, y = month_df, by = "month_num") |> 
  select(year, month, close, -month_num, -day)

head(snp_df)
```


```{r, unemployment cleaning}
unemployment_df <- unemployment_raw |> 
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent_unemployed"
  )

head(unemployment_df)

```





